### PR TITLE
Better handling of boundary events

### PR DESCRIPTION
**Pull request by arnodelorme**

### CODE REVIEW

**Comment by widmann** [comment]
Thanks, but I think I'm missing the point. The dcArray is not actually stored in the data. It is only used for internal purposes (avoiding to filter over DC offsets). I do not see a way how this could lead to duplicate boundary events. Would you mind sending a test case?
Thanks!

**Comment by arnodelorme** [comment]
This is because, now, for EEGLAB internal consistency reasons, if data is removed at the end, a boundary event is inserted to indicate what portion of data was removed.
In the current code, that could lead to a duplicate event at the end because dcArray adds this final event as well.

**Comment by widmann** [comment]
Hm, test case would have helped. So, issue is that firfilt.m throws an error rather than returns duplicates boundary event (as I understood your description).

The actual issue is that there is a boundary event outside data range. The final `EEG.pnts + 1` has a different intention and is not actually interpreted as boundary. This is coincidence. The issue will occur with any boundary event latency outside data range. Also fixed for the other/future code path (currently used with usefftfilt or minphase filtering options).

Fixed in 4b2701d. Please update reference in EEGLAB plugins. New version issued.

**Comment by arnodelorme** [comment]
> Hm, test case would have helped. So, issue is that firfilt.m throws an error rather than returns duplicates boundary event (as I understood your description).

Correct.

> The actual issue is that there is a boundary event outside data range. The final EEG.pnts + 1 has a different intention and is not actually interpreted as boundary. This is coincidence. The issue will occur with any boundary event latency outside data range.

Yes, but this is handled by the eeg_checkset function that will check for the presence of those events.

> Also fixed for the other/future code path (currently used with usefftfilt or minphase filtering options).

Thank you

> 
> Fixed in 4b2701d. Please update reference in EEGLAB plugins. New version issued.

**Comment by widmann** [comment]
Dear Arno,
your patch only fixed one of two code paths. Please update the firfilt submodule URL in the EEGLAB repo to commit 4b2701d. Otherwise we will see many more bug reports like this one in the next days:
https://github.com/widmann/firfilt/pull/14
Thanks, Andreas

**Pull request closed without merging**
